# Generated by Django 4.0.4 on 2022-05-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_carte', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=50)),
                ('hired_on', models.DateField(null=True)),
                ('position', models.CharField(choices=[('Manager', 'manager'), ('Developer', 'developer'), ('Designer', 'designer')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEAM', models.CharField(choices=[('DevOps team', 'devops team'), ('Dev team', 'dev team'), ('Design team', 'design team')], max_length=50, null=True)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='employee.employee')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
